import {StyleSheet} from 'react-native';
import tw from 'tailwind-react-native-classnames';

const styles = StyleSheet.create({
  container: tw`flex-1 bg-gray-100`,
  scrollView: tw`flex-1`,
  textContainer: tw`mt-4 ml-5 mb-2`,
  text: tw`text-lg text-black uppercase font-extrabold`,
  headingContainer: tw`flex-row`,
  slash: tw`ml-1.5`,
  headingText: tw`ml-2 text-gray-500 capitalize`,
  card: tw`w-11/12 min-h-0 flex-1 m-3 ml-5 bg-white shadow-md`,
  heading: tw`p-3 ml-2 mt-2 uppercase text-lg font-extrabold text-gray-600`,
  line: tw`w-full h-0.5 bg-gray-100`,
  savePressableContainer: tw`flex-1 justify-end items-end mr-2 mb-4 mt-4`,
  savePressable: tw`w-5/12 h-12 rounded justify-center items-center bg-red-500`,
  savePressableText: tw`text-white capitalize text-base text-center`,
  tabsPressable: tw`p-4`,
  tabsText: tw`text-sm font-extrabold uppercase`,
  wouldLikeTextContainer: tw`ml-4 mt-4`,
  wouldLikeText: tw`text-base text-gray-800`,
  engagingTextContainer: tw`ml-4 mt-3`,
  engagingText: tw`text-sm text-gray-400 pr-4`,
  thumbStyle: tw`bg-white h-10 w-10`,
  trackBarStyle: tw`h-11 m-4`,
  checkIconContainer: tw`flex-1 justify-center items-center`,
  currencyInputContainer: tw`m-4 mr-7 mt-0`,
  currencyLabelText: tw`pb-2 capitalize text-gray-700 text-base`,
  star: tw`text-red-400 text-base`,
  currencyInput: tw`w-full h-11 border-2 border-green-600 rounded mb-2 pl-1`,
  companyInput: tw`w-full h-40 border-2 border-green-600 rounded pl-1`,
  hashTagText: tw`text-gray-400 text-xs mt-1`,
  additionalContainer: tw`ml-2`,
  additionalText: tw`ml-2 text-base text-black capitalize mb-1`,
  itemCenter: tw`items-center`,
  allowText: tw`text-base text-gray-600 capitalize`,
  helloContainer: tw`ml-6 mt-3 items-center mb-5`,
  rounded: tw`w-1 h-1 rounded-full bg-gray-400 mr-3`,
  helloText: tw`text-gray-400 text-base`,
  marginLeftZero: tw`ml-0`,
  marginBottomFour: tw`mb-4`,
  marginTop: tw`mt-3`,
  textInput: tw`w-11/12 h-12 border-2 border-gray-200 rounded`,
  pickerContainer: tw`justify-center`,
  customRewardsText: tw`text-lg text-gray-500`,
});

export default styles;
