import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalBody: {
    width: '90%',
    height: '90%',
    backgroundColor: '#fff',
    borderRadius: 5,
  },
  cardHeadingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 15,
    marginVertical: 20,
  },
  line: {
    width: '100%',
    height: '0.2%',
    backgroundColor: '#b3b3b3',
  },
  cardHeadingText: {
    textTransform: 'capitalize',
    fontSize: 20,
    fontWeight: 'bold',
  },
  closeIconContainer: {
    flex: 1,
    alignItems: 'flex-end',
  },
  closePressabel: {
    width: 30,
    height: 30,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardLine: {
    width: '100%',
    height: 2,
    backgroundColor: '#e9ecef',
  },
  holidayAndSickContainer: {
    flexDirection: 'row',
    marginVertical: 10,
    marginHorizontal: 2,
  },
  holidayCard: {
    width: '45%',
    height: 100,
    backgroundColor: '#fff',
    elevation: 10,
    borderRadius: 5,
    marginHorizontal: 15,
    paddingVertical: 10,
    paddingHorizontal: 10,
  },
  holiday: {
    textTransform: 'uppercase',
    color: '#808495',
    fontWeight: '300',
  },
  holidayNumContainer: {
    flexDirection: 'row',
    marginVertical: 4,
    marginHorizontal: 1,
  },
  numOfHoliday: {
    color: '#006f44',
    fontSize: 18,
    fontWeight: '400',
  },
  hoursAvai: {
    color: '#808495',
    fontSize: 12,
    textTransform: 'capitalize',
    textAlignVertical: 'bottom',
    marginVertical: 3,
    marginHorizontal: 2,
  },
  hoursUseContainer: {
    flexDirection: 'row',
  },
  numOfHoursUse: {
    fontSize: 12,
    fontWeight: '400',
    color: '#ff4c52',
  },
  hoursUseText: {
    color: '#808495',
    fontSize: 10,
    marginHorizontal: 3,
    marginVertical: 2,
    textTransform: 'capitalize',
  },
  sickCard: {
    width: '45%',
    height: 100,
    backgroundColor: '#fff',
    elevation: 10,
    borderRadius: 5,
    paddingVertical: 10,
    paddingHorizontal: 10,
  },
  reqTypeContainer: {
    width: '38%',
    height: 35,
    justifyContent: 'center',
    alignItems: 'center',
  },
  reqType: {
    color: '#212529',
    textTransform: 'capitalize',
  },
  pressable: {
    flexDirection: 'row',
    width: '90%',
    height: 45,
    borderWidth: 0.6,
    borderRadius: 5,
    alignItems: 'center',
    alignSelf: 'center',
  },
  dropIconContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'flex-end',
    marginHorizontal: 10,
  },
  dropIcon: {
    marginBottom: -13,
  },
  text: {
    marginHorizontal: 10,
  },
  star: {
    fontSize: 18,
    color: '#ff4c52',
  },
  dateRange: {
    width: '34%',
    height: 35,
    justifyContent: 'center',
    alignItems: 'center',
  },
  dateRangeText: {
    color: '#212529',
  },
  datePickContainer: {
    flexDirection: 'row',
    width: '96%',
  },
  fromTextInput: {
    flexDirection: 'row',
    width: '42%',
    height: 45,
    borderWidth: 0.6,
    borderRadius: 5,
    alignItems: 'center',
    alignSelf: 'center',
    marginHorizontal: 15,
    paddingHorizontal: 10,
  },
  reviewerContainer: {
    width: '30%',
    height: 35,
    justifyContent: 'center',
    alignItems: 'center',
  },
  commentTextContainer: {
    width: '28%',
    height: 35,
    justifyContent: 'center',
    alignItems: 'center',
  },
  commentText: {
    color: '#212529',
    textTransform: 'capitalize',
  },
  commentTextInput: {
    flexDirection: 'row',
    width: '90%',
    height: 45,
    borderWidth: 0.6,
    borderRadius: 5,
    alignItems: 'center',
    alignSelf: 'center',
  },
  cancelAndSendReqContainer: {
    marginVertical: 35,
    width: '85%',
    height: 60,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'flex-end',
    marginHorizontal: 20,
  },
  cancelPressableText: {
    color: '#fff',
    fontSize: 20,
    textTransform: 'capitalize',
  },
  sendReqPressable: {
    width: '51%',
    height: 50,
    marginHorizontal: 5,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  cancelPressable: {
    width: '51%',
    height: 50,
    marginHorizontal: 5,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  scrollView: {
    flex: 1,
  },
});

export default styles;
