import {StyleSheet} from 'react-native';
import tw from 'tailwind-react-native-classnames';

const styles = StyleSheet.create({
  container: tw`flex-1 bg-gray-100`,
  scrollView: tw`flex-1`,
  textContainer: tw`mt-5 ml-3 mb-2 items-center`,
  text: tw`text-lg text-black uppercase font-extrabold`,
  headingContainer: tw`flex-row`,
  slash: tw`ml-1.5`,
  headingText: tw`ml-2 text-gray-500 capitalize`,
  card: tw`w-11/12 min-h-0 flex-1 m-3 self-center bg-white shadow-md`,
  heading: tw`p-3 ml-2 mt-2 uppercase text-lg font-extrabold text-gray-600`,
  line: tw`w-full h-0.5 bg-gray-100`,
  cancelPressableContainer: tw`flex-1 justify-end items-end mr-4`,
  cancelPressable: tw`w-5/12 h-12 rounded justify-center items-center bg-red-500`,
  cancelPressableText: tw`text-white capitalize text-base`,
  advancedSettingsTab: tw`w-5/12 h-12 bg-gray-100 justify-center items-center p-2`,
  importTab: tw`w-3/12 h-12 bg-gray-100 justify-center items-center`,
  complaintsTab: tw`w-4/12 h-12 bg-gray-100 justify-center items-center`,
  tabsText: tw`text-sm font-extrabold uppercase`,
  itemsCenter: tw`items-center ml-2 p-5`,
  addEmployeeText: tw`text-base`,
  generalSetting: tw`items-center ml-2 mt-4`,
  generalSettingTwo: tw`items-center ml-2`,
  selectAll: tw`capitalize font-extrabold`,
  switchContainer: tw`flex-1 justify-center items-end`,
  jobTabsContainer: tw`ml-4 mt-2`,
  jobPositionTab: tw`w-5/12 h-12 border-2 border-gray-100 rounded justify-center items-center`,
  tabText: tw`capitalize text-sm`,
  officesTab: tw`w-5/12 h-12 border-2 border-gray-100 rounded justify-center items-center ml-2`,
  workStatusesTab: tw`w-5/12 h-12 border-2 border-gray-100 rounded justify-center items-center ml-2`,
  terminationReasonTab: tw`w-6/12 h-12 border-2 border-gray-100 rounded justify-center items-center ml-2`,
  levelTab: tw`w-4/12 h-12 border-2 border-gray-100 rounded justify-center items-center`,
  addNewPressableContainer: tw`flex-1 justify-end items-center mt-5`,
  addNewPressable: tw`w-11/12 h-10 rounded justify-center items-center bg-red-500`,
  iconsContainer: tw`flex-1 justify-end items-end mr-3`,
  icon: tw`w-6 h-6 justify-center items-center rounded-xl ml-2`,
  degreeHeading: tw`p-3 ml-1 mt-2 capitalize text-2xl font-extrabold text-gray-600`,
  activeTextContainer: tw`bg-green-500 pl-1.5 pr-1.5 h-4 rounded-full ml-4`,
  activeText: tw`text-xs text-white`,
});

export default styles;
