import {StyleSheet} from 'react-native';
import tw from 'tailwind-react-native-classnames';

const styles = StyleSheet.create({
  container: tw`flex-1 bg-gray-100`,
  scrollView: tw`flex-1`,
  textContainer: tw`mt-5 ml-3 mb-2`,
  text: tw`text-lg text-black uppercase font-extrabold`,
  headingContainer: tw`flex-row`,
  slash: tw`ml-1.5`,
  headingText: tw`ml-2 text-gray-500 capitalize`,
  marginTop: tw`mt-2`,
  card: tw`w-11/12 min-h-0 flex-1 m-3 self-center bg-white shadow-md`,
  heading: tw`p-3 ml-2 mt-2 uppercase text-lg font-extrabold text-gray-600`,
  line: tw`w-full h-0.5 bg-gray-100`,
  createPressableContainer: tw`flex-1 justify-end items-end mr-2 mb-4 mt-4`,
  createPressable: tw`w-11/12 h-10 p-1 rounded justify-center items-center bg-red-500`,
  createPressableText: tw`text-white capitalize text-xs text-center`,
  customTabCard: tw`w-7/12 self-center min-h-0 flex-1 m-5 bg-white shadow-md`,
  iconsContainer: tw`flex-1 justify-end items-end mr-2`,
  iconsAndContentContainer: tw`bg-gray-50 pb-8 pt-8 pl-2`,
  contentText: tw`flex-1 text-base text-black font-extrabold`,
  marginLeft: tw`ml-2`,
  dropHereTextContainer: tw`border-dashed border-2 pt-7 pb-7 border-gray-200 bg-blue-50 m-2 justify-center items-center`,
  dropHereText: tw`capitalize font-extrabold text-gray-400 text-base`,
  refineText: tw`uppercase text-black font-extrabold text-base`,
  arrowIcon: tw`ml-3`,
  fieldInputContainer: tw`m-4 ml-2 mr-7 mt-0`,
  fieldLabelText: tw`pb-2 capitalize text-gray-700 text-base`,
  fieldInput: tw`w-full h-11 border-2 border-gray-200 rounded pl-1`,
  clearPressable: tw`w-3/12 h-12 rounded justify-center items-center border-2 border-green-500`,
  searchPressable: tw`bg-green-600 w-3/12`,
  clearPressableText: tw`text-green-500 capitalize text-base text-center`,
  selfEnd: tw`self-end mr-7`,
  marginRight: tw`mr-2`,
  savePressable: tw`w-5/12 h-12 rounded justify-center items-center bg-red-500`,
  savePressableText: tw`text-white capitalize text-base text-center`,
  pickerContainer: tw`justify-center`,
  marginBottom: tw`mb-3`,
  dragAFieldCard: tw`w-11/12 h-16 mr-5 ml-2 mt-4 bg-white border-2 border-gray-100 flex-row items-center rounded`,
  dragAFieldText: tw`ml-3 text-base text-black`,
  gotItPressable: tw`border-2 border-gray-200 p-2 rounded`,
  gotItText: tw`capitalize text-base`,
  tableContainer: tw`bg-blue-50 justify-around p-4`,
  tableHeading: tw`capitalize text-base text-black`,
  selectIcon: tw`mt-0.5 mr-1`,
  actionsText: tw`capitalize text-base text-gray-500`,
  holidayTable: tw`flex-1 justify-between`,
  holidayTableContainer: tw`flex-col p-5 w-6/12`,
  holidTableTextContainer: tw`bg-blue-100 p-2`,
  tableHeadingText: tw`capitalize text-base text-gray-500 font-extrabold`,
  tableTitleText: tw`capitalize mt-2 text-sm text-black w-40 font-extrabold`,
  commentChildText: tw`capitalize mt-2 text-sm text-black w-32`,
  tableDateText: tw`text-xs text-gray-400`,
  tableSubtitleText: tw`mt-2 text-sm text-gray-500 w-40`,
});

export default styles;
