export const FETCH_USER_DATA = 'FETCH_USER_DATA';
export const FETCH_PROFILE_DETAILS_DATA = 'FETCH_PROFILE_DETAILS_DATA';
export const FETCH_EDIT_BIO_DATA = 'FETCH_EDIT_BIO_DATA';
export const FETCH_EMERGENCY_CONTACT_DATA = 'FETCH_EMERGENCY_CONTACT_DATA';
export const FETCH_CONTACT_INFORMATION_DATA = 'FETCH_CONTACT_INFORMATION_DATA';
export const FETCH_EDUCATION_DATA = 'FETCH_EDUCATION_DATA';
export const FETCH_LICENSES_AND_CERTIFICATIONS_DATA =
  'FETCH_LICENSES_AND_CERTIFICATIONS_DATA';
export const PRIMARY_COLOR = 'PRIMARY_COLOR';
export const PRIMARY_HOVER_COLOR = 'PRIMARY_HOVER_COLOR';
export const GET_TASK_LISTS = 'GET_TASK_LISTS';
export const CREATE_TASK_LISTS = 'CREATE_TASK_LISTS';
export const PARAM_LISTS_DATA = 'PARAM_LISTS_DATA';
export const FETCH_COMPANY_EMPLOYEES = 'FETCH_COMPANY_EMPLOYEES';
