export const FETCH_USER_DATA = 'FETCH_USER_DATA';
export const FETCH_PROFILE_DETAILS_DATA = 'FETCH_PROFILE_DETAILS_DATA';
export const FETCH_EDIT_BIO_DATA = 'FETCH_EDIT_BIO_DATA';
export const FETCH_EMERGENCY_CONTACT_DATA = 'FETCH_EMERGENCY_CONTACT_DATA';
export const FETCH_CONTACT_INFORMATION_DATA = 'FETCH_CONTACT_INFORMATION_DATA';
