import {StyleSheet} from 'react-native';
import tw from 'tailwind-react-native-classnames';

const styles = StyleSheet.create({
  container: tw`flex-1 justify-center items-center pt-10`,
  scrollView: tw`flex-1`,
  modalBody: tw`w-11/12 h-full flex-1 bg-white mb-10`,
  closeIconContainer: tw`flex-1 justify-center items-end`,
  cardHeadingContainer: tw`p-5 flex-row`,
  closePressabel: tw`w-7 h-7 justify-center items-center rounded-full`,
  cardHeadingText: tw`capitalize text-lg text-gray-500 font-extrabold`,
  line: tw`w-full h-0.5 bg-gray-100`,
  rewardTextContainer: tw`ml-4 mt-4`,
  reward: tw`capitalize text-gray-500 text-base`,
  rewardTextInput: tw`w-11/12 h-12 border-2 border-gray-300 self-center mt-2 rounded pl-2`,
  cancelAndSubmitContainer: tw`m-4 flex-row flex-1 justify-end items-end`,
  cancelPressable: tw`w-4/12 h-12 rounded justify-center items-center`,
  submitPressable: tw`w-6/12 h-12 ml-2 rounded justify-center items-center`,
  cancelPressableText: tw`text-white capitalize text-lg`,
  pickerContainer: tw`justify-center pl-0`,
  star: tw`text-red-500`,
  descriptionTextInput: tw`w-11/12 h-20 border-2 border-gray-300 self-center mt-2 rounded pl-2`,
  uploadNewImagePressable: tw`w-6/12 h-12 ml-2 rounded justify-center items-center self-center mt-4 mr-2`,
  svgImageContainer: tw`w-40 h-40 shadow self-center mt-4 justify-center items-center rounded`,
  newRewardImage: tw`w-32 h-32`,
  tabsContainer: tw`flex-row ml-4 mt-5 mr-4`,
  tabLinesContainer: tw`flex-row flex-1`,
  tabsText: tw`capitalize text-sm`,
  roleInfoTab: tw`border-r-2 border-t-2 border-l-2 rounded-tl rounded-tr border-gray-100 p-6 pb-4 pt-4`,
  roleResourcesTab: tw`border-r-2 border-t-2 border-l-2 rounded-tl rounded-tr border-gray-100 p-6 pb-4 pt-4 ml-0.5`,
  marginTopFour: tw`mt-4`,
  widthFour: tw`w-4`,
  lineContainer: tw`flex-1 justify-end items-end`,
  enableAndDisablePressableContainer: tw`flex-1 flex-row border-2 border-gray-100 mr-2 self-end p-0.5 rounded mt-2`,
  enablePressable: tw`w-6/12 h-12 rounded justify-center items-center`,
  disablePressable: tw`w-4/12 h-12 rounded justify-center items-center`,
  enableAndDisablePressableText: tw`capitalize text-lg text-center`,
  resourcesAccessContainer: tw`bg-gray-50 m-2 pb-2 mt-6`,
  resourcesAccess: tw`ml-3 mt-2 text-black text-base uppercase flex-1`,
  clearPressable: tw`w-3/12 h-12 border-2 border-green-500 rounded justify-center items-center`,
  searchPressable: tw`w-3/12 h-12 ml-2 rounded justify-center items-center`,
  clearPressableText: tw`text-green-500 capitalize text-lg`,
  headingContainer: tw`flex-row`,
  userTable: tw`flex-1 items-center ml-5 pl-14 pr-8 h-11 w-11/12 h-10 mt-3 bg-blue-100`,
  marginRightFive: tw`mr-5`,
  nameHeadingText: tw`w-24 capitalize text-base font-extrabold text-gray-500`,
  emailHeadingText: tw`capitalize text-base font-extrabold text-gray-500 ml-3 w-40`,
  roleHeadingText: tw`capitalize text-base font-extrabold text-gray-500 ml-3 w-24`,
  userStatusHeadingText: tw`capitalize text-base font-extrabold text-gray-500 ml-2 w-12`,
  userHeadingItemsContainer: tw`flex-1 items-center w-11/12 h-10 ml-5 pl-2 mt-3 pr-8`,
  nameTableItemText: tw`w-24 text-sm text-gray-500`,
  emailTableItemText: tw`ml-3 w-40 text-sm text-gray-500`,
  roleTableItemText: tw`ml-3 w-24 text-sm text-gray-500`,
  userStatusTableItemText: tw`w-12 pb-0.5 pt-0.5 mr-2 rounded-full text-white text-center text-xs`,
  tableLine: tw`w-11/12 mt-5 self-center`,
  itemCenter: tw`items-center`,
  switchText: tw`uppercase text-sm font-extrabold text-gray-600`,
});

export default styles;
