export const departmentData = [
  {
    name: 'Design',
  },
  {
    name: 'Development',
  },
  {
    name: 'Founders',
  },
  {
    name: 'HR',
  },
  {
    name: 'Marketing',
  },
  {
    name: 'Product',
  },
  {
    name: 'Sales',
  },
  {
    name: 'Support',
  },
];

export const positionData = [
  {
    name: 'Content Writer',
  },
  {
    name: 'Customer Support',
  },
  {
    name: 'Designer',
  },
  {
    name: 'Developer',
  },
  {
    name: 'Founder',
  },
  {
    name: 'HR',
  },
  {
    name: 'Marketer',
  },
  {
    name: 'PM/PO',
  },
  {
    name: 'Sales',
  },
];

export const newTimeOffReqData = [
  {
    name: 'Holiday',
  },
  {
    name: 'Sick',
  },
];

export const yearData = [
  {
    name: '2012',
  },
  {
    name: '2013',
  },
  {
    name: '2014',
  },
  {
    name: '2015',
  },
  {
    name: '2016',
  },
  {
    name: '2017',
  },
  {
    name: '2018',
  },
  {
    name: '2019',
  },
  {
    name: '2020',
  },
  {
    name: '2021',
  },
  {
    name: '2022',
  },
];

export const profileData = [
  {
    name: 'Holiday',
  },
  {
    name: 'Sick',
  },
];

export const timeData = [
  {name: '00:00am'},
  {name: '00:30am'},
  {name: '01:00am'},
  {name: '01:30am'},
  {name: '02:00am'},
  {name: '02:30am'},
  {name: '03:00am'},
  {name: '03:30am'},
  {name: '04:00am'},
  {name: '04:30am'},
  {name: '05:00am'},
  {name: '05:30am'},
  {name: '06:00am'},
  {name: '06:30am'},
  {name: '07:00am'},
  {name: '07:30am'},
  {name: '08:00am'},
  {name: '08:30am'},
  {name: '09:00am'},
  {name: '09:30am'},
  {name: '10:00am'},
  {name: '10:30am'},
  {name: '11:00am'},
  {name: '11:30am'},
  {name: '12:00pm'},
  {name: '12:30pm'},
  {name: '13:00pm'},
  {name: '13:30pm'},
  {name: '14:00pm'},
  {name: '14:30pm'},
  {name: '15:00pm'},
  {name: '15:30pm'},
  {name: '16:00pm'},
  {name: '16:30pm'},
  {name: '17:00pm'},
  {name: '17:30pm'},
  {name: '18:00pm'},
  {name: '18:30pm'},
  {name: '19:00pm'},
  {name: '19:30pm'},
  {name: '20:00pm'},
  {name: '20:30pm'},
  {name: '21:00pm'},
  {name: '21:30pm'},
  {name: '22:00pm'},
  {name: '22:30pm'},
  {name: '23:00pm'},
  {name: '23:30pm'},
];

export const genderData = [
  {name: 'Male'},
  {name: 'Female'},
  {name: 'Gender-Neutral'},
];

export const languageData = [
  {name: ''},
  {name: 'English'},
  {name: 'Russian'},
  {name: 'Ukrainian'},
];

export const zoneData = [
  {name: 'Africa/Abidjan'},
  {name: 'Africa/Accra'},
  {name: 'Africa/Addis_Ababa'},
  {name: 'Africa/Algiers'},
  {name: 'Africa/Asmara'},
  {name: 'Africa/Bamako'},
  {name: 'Africa/Bangui'},
  {name: 'Africa/Banjul'},
  {name: 'America/Adak'},
  {name: 'America/Anchorage'},
  {name: 'America/Anguilla'},
  {name: 'America/Antigua'},
  {name: 'America/Araguaina'},
  {name: 'America/Argentina/Buenos_Aires'},
  {name: 'Antarctica/Casey'},
  {name: 'Antarctica/Davis'},
  {name: 'Antarctica/DumontDUrvilla'},
  {name: 'Antarctica/Macquarie'},
  {name: 'Antarctica/Mawson'},
  {name: 'Antarctica/McMurdi'},
  {name: 'Antarctica/Palmer'},
  {name: 'Asia/Aden'},
  {name: 'Asia/Almaty'},
  {name: 'Asia/Amman'},
  {name: 'Asia/Anadyr'},
  {name: 'Asia/Aqtau'},
  {name: 'Asia/Aqtobe'},
  {name: 'Asia/Ashghabat'},
  {name: 'Asia/Atyrau'},
  {name: 'Europe/Amsterdam'},
  {name: 'Europe/Andora'},
  {name: 'Europe/AstraKhan'},
  {name: 'Europe/Athens'},
  {name: 'Europe/Belgrade'},
  {name: 'Europe/Berlin'},
  {name: 'Europe/Bratislava'},
  {name: 'Europe/Brussels'},
  {name: 'Europe/Busharest'},
  {name: 'Pacific/Apia'},
  {name: 'Pacific/Auckland'},
  {name: 'Pacific/Bougainville'},
  {name: 'Pacific/Chatham'},
  {name: 'Pacific/Chuuk'},
  {name: 'Pacific/Easter'},
  {name: 'Pacific/Efat'},
  {name: 'Pacific/Fakaofo'},
];

export const employmentLevelData = [
  {name: 'Junior'},
  {name: 'Lead'},
  {name: 'Regular'},
  {name: 'Senior'},
  {name: 'Trainee'},
];

export const countryData = [
  {name: 'Albania'},
  {name: 'Algeria'},
  {name: 'Andorra'},
  {name: 'Angola'},
  {name: 'Antigua'},
  {name: 'Argentina'},
  {name: 'Armenia'},
  {name: 'Australia'},
  {name: 'Austria'},
  {name: 'Azerbaijan'},
  {name: 'Bahamas'},
  {name: 'Bahrain'},
  {name: 'Bangladesh'},
  {name: 'Barbados'},
  {name: 'Belarus'},
  {name: 'Belgium'},
  {name: 'Belize'},
  {name: 'Benin'},
  {name: 'Bhutan'},
  {name: 'Bolivia'},
  {name: 'Bosnia'},
  {name: 'Botswana'},
  {name: 'Brazil'},
  {name: 'Brunei'},
  {name: 'Bulgaria'},
  {name: 'Burkina'},
  {name: 'Burundi'},
  {name: 'Cabo Verde'},
  {name: 'Cambodia'},
  {name: 'Cameroon'},
  {name: 'Canada'},
  {name: 'Central'},
  {name: 'Chad'},
  {name: 'Chile'},
  {name: 'China'},
  {name: 'Comoros'},
  {name: 'Congo'},
  {name: 'Cook Islands'},
  {name: 'Costa Rica'},
  {name: 'Croatia'},
  {name: 'Cuba'},
  {name: 'Cyprus'},
  {name: 'Czechia'},
  {name: 'Côte d Ivoire'},
  {name: 'Democratic Peoples'},
  {name: 'Democratic'},
  {name: 'Denmark'},
  {name: 'Djibouti'},
  {name: 'Dominica'},
  {name: 'Dominican'},
  {name: 'Ecuador'},
  {name: 'Egypt'},
  {name: 'El Salvador'},
  {name: 'Equatorial Guinea'},
  {name: 'Eritrea'},
  {name: 'Estonia'},
  {name: 'Eswatini'},
  {name: 'Ethiopia'},
  {name: 'Faroe Islands'},
  {name: 'Fiji'},
  {name: 'Finland'},
  {name: 'France'},
  {name: 'Gabon'},
  {name: 'Gambia'},
  {name: 'Georgia'},
  {name: 'Germany'},
  {name: 'Ghana'},
  {name: 'Greece'},
  {name: 'Grenada'},
  {name: 'Guatemala'},
  {name: 'Guinea'},
  {name: 'Guinea-Bissau'},
  {name: 'Guyana'},
  {name: 'Haiti'},
  {name: 'Honduras'},
  {name: 'Hungary'},
  {name: 'Iceland'},
  {name: 'India'},
  {name: 'Iran'},
  {name: 'Iraq'},
  {name: 'Ireland'},
  {name: 'Israel'},
  {name: 'Italy'},
  {name: 'Jamaica'},
  {name: 'Japan'},
  {name: 'Jordan'},
  {name: 'Kenya'},
  {name: 'Kiribati'},
  {name: 'Kuwait'},
  {name: 'Kyrgyzstan'},
  {name: 'Lao Peoples'},
  {name: 'Latvia'},
  {name: 'Lebanon'},
  {name: 'Lesotho	Liberia'},
  {name: 'Libya'},
  {name: 'Lithuania'},
  {name: 'Luxembourg'},
  {name: 'Madagascar'},
  {name: 'Malawi'},
  {name: 'Malaysia'},
  {name: 'Maldives'},
  {name: 'Mali'},
  {name: 'Malta'},
  {name: 'Marshall Islands'},
  {name: 'Mauritania'},
  {name: 'Mauritius'},
  {name: 'Mexico'},
  {name: 'Micronesia'},
  {name: 'Monaco'},
  {name: 'Mongolia'},
  {name: 'Montenegro'},
  {name: 'Morocco'},
  {name: 'Mozambique'},
  {name: 'Myanmar'},
  {name: 'Namibia'},
  {name: 'Nauru'},
  {name: 'Nepal'},
  {name: 'Netherlands'},
  {name: 'New Zealand'},
  {name: 'Nicaragua'},
  {name: 'Niger'},
  {name: 'Nigeria'},
  {name: 'Niue'},
  {name: 'North Macedonia'},
  {name: 'Norway'},
  {name: 'Oman'},
  {name: 'Pakistan'},
  {name: 'Palau'},
  {name: 'Panama'},
  {name: 'Papua New Guinea'},
  {name: 'Paraguay'},
  {name: 'Peru'},
  {name: 'Philippines'},
  {name: 'Poland'},
  {name: 'Portugal'},
  {name: 'Qatar'},
  {name: 'Romania'},
  {name: 'Russian'},
  {name: 'Rwanda'},
  {name: 'Saint Kitts'},
  {name: 'Saint Lucia'},
  {name: 'Saint Vincent'},
  {name: 'Samoa'},
  {name: 'San Marino'},
  {name: 'Sao Tome'},
  {name: 'Saudi Arabia'},
  {name: 'Senegal'},
  {name: 'Serbia'},
  {name: 'Seychelles'},
  {name: 'Sierra Leone'},
  {name: 'Singapore'},
  {name: 'Slovakia'},
  {name: 'Slovenia'},
  {name: 'Solomon Islands'},
  {name: 'Somalia'},
  {name: 'South Africa'},
  {name: 'South Sudan'},
  {name: 'Spain'},
  {name: 'Sri Lanka'},
  {name: 'Sudan'},
  {name: 'Suriname'},
  {name: 'Sweden'},
  {name: 'Switzerland'},
  {name: 'Syrian Arab'},
  {name: 'Tajikistan'},
  {name: 'Thailand'},
  {name: 'Timor-Leste'},
  {name: 'Togo'},
  {name: 'Tokelau'},
  {name: 'Tonga'},
  {name: 'Trinidad'},
  {name: 'Tunisia'},
  {name: 'Turkey'},
  {name: 'Turkmenistan'},
  {name: 'Tuvalu'},
  {name: 'Uganda'},
  {name: 'Ukraine'},
  {name: 'United Arab Emirates'},
  {name: 'United Kingdom'},
  {name: 'United States of America'},
  {name: 'Uruguay'},
  {name: 'Uzbekistan'},
  {name: 'Vanuatu'},
  {name: 'Venezuela'},
  {name: 'Viet Nam'},
  {name: 'Yemen'},
  {name: 'Zambia'},
  {name: 'Zimbabwe'},
];

export const regionData = [
  {name: 'Azad Kashmir'},
  {name: 'Balochistan'},
  {name: 'Federally Administered Tribal Areas'},
  {name: 'Islamabad'},
  {name: 'North-West Frontier'},
  {name: 'Northern Areas'},
  {name: 'Punjab'},
  {name: 'Sindh'},
];

export const monthsNameData = [
  {name: 'Month'},
  {name: 'January'},
  {name: 'February'},
  {name: 'March'},
  {name: 'April'},
  {name: 'May'},
  {name: 'June'},
  {name: 'July'},
  {name: 'August'},
  {name: 'September'},
  {name: 'October'},
  {name: 'Novebmer'},
  {name: 'December'},
];

export const issueDateData = [
  {name: 'Year'},
  {name: '2022'},
  {name: '2021'},
  {name: '2020'},
  {name: '2019'},
  {name: '2018'},
  {name: '2017'},
  {name: '2016'},
  {name: '2015'},
  {name: '2014'},
  {name: '2013'},
  {name: '2012'},
  {name: '2011'},
  {name: '2010'},
  {name: '2009'},
  {name: '2008'},
  {name: '2007'},
  {name: '2006'},
  {name: '2005'},
  {name: '2004'},
  {name: '2003'},
  {name: '2002'},
  {name: '2001'},
  {name: '2000'},
  {name: '1999'},
  {name: '1998'},
  {name: '1997'},
  {name: '1996'},
  {name: '1995'},
  {name: '1994'},
  {name: '1993'},
  {name: '1992'},
  {name: '1991'},
  {name: '1990'},
  {name: '1989'},
  {name: '1988'},
  {name: '1987'},
  {name: '1986'},
  {name: '1985'},
  {name: '1984'},
  {name: '1983'},
  {name: '1982'},
  {name: '1981'},
  {name: '1980'},
  {name: '1979'},
  {name: '1978'},
  {name: '1977'},
  {name: '1976'},
  {name: '1975'},
  {name: '1974'},
  {name: '1973'},
  {name: '1972'},
  {name: '1971'},
  {name: '1970'},
  {name: '1969'},
  {name: '1968'},
  {name: '1967'},
  {name: '1966'},
  {name: '1965'},
  {name: '1964'},
  {name: '1963'},
  {name: '1962'},
  {name: '1961'},
  {name: '1960'},
  {name: '1959'},
  {name: '1958'},
  {name: '1957'},
  {name: '1956'},
  {name: '1955'},
  {name: '1954'},
  {name: '1953'},
  {name: '1952'},
  {name: '1951'},
  {name: '1950'},
  {name: '1949'},
  {name: '1948'},
  {name: '1947'},
  {name: '1946'},
  {name: '1945'},
  {name: '1944'},
  {name: '1943'},
  {name: '1942'},
  {name: '1941'},
  {name: '1940'},
  {name: '1939'},
  {name: '1938'},
  {name: '1937'},
  {name: '1936'},
  {name: '1935'},
  {name: '1934'},
  {name: '1933'},
  {name: '1932'},
  {name: '1931'},
  {name: '1930'},
  {name: '1929'},
  {name: '1928'},
  {name: '1927'},
  {name: '1926'},
  {name: '1925'},
  {name: '1924'},
  {name: '1923'},
  {name: '1922'},
];

export const expirationDateData = [
  {name: 'Year'},
  {name: '2032'},
  {name: '2031'},
  {name: '2030'},
  {name: '2029'},
  {name: '2028'},
  {name: '2027'},
  {name: '2026'},
  {name: '2025'},
  {name: '2024'},
  {name: '2023'},
  {name: '2022'},
  {name: '2021'},
  {name: '2020'},
  {name: '2019'},
  {name: '2018'},
  {name: '2017'},
  {name: '2016'},
  {name: '2015'},
  {name: '2014'},
  {name: '2013'},
  {name: '2012'},
  {name: '2011'},
  {name: '2010'},
  {name: '2009'},
  {name: '2008'},
  {name: '2007'},
  {name: '2006'},
  {name: '2005'},
  {name: '2004'},
  {name: '2003'},
  {name: '2002'},
  {name: '2001'},
  {name: '2000'},
  {name: '1999'},
  {name: '1998'},
  {name: '1997'},
  {name: '1996'},
  {name: '1995'},
  {name: '1994'},
  {name: '1993'},
  {name: '1992'},
  {name: '1991'},
  {name: '1990'},
  {name: '1989'},
  {name: '1988'},
  {name: '1987'},
  {name: '1986'},
  {name: '1985'},
  {name: '1984'},
  {name: '1983'},
  {name: '1982'},
  {name: '1981'},
  {name: '1980'},
  {name: '1979'},
  {name: '1978'},
  {name: '1977'},
  {name: '1976'},
  {name: '1975'},
  {name: '1974'},
  {name: '1973'},
  {name: '1972'},
  {name: '1971'},
  {name: '1970'},
  {name: '1969'},
  {name: '1968'},
  {name: '1967'},
  {name: '1966'},
  {name: '1965'},
  {name: '1964'},
  {name: '1963'},
  {name: '1962'},
  {name: '1961'},
  {name: '1960'},
  {name: '1959'},
  {name: '1958'},
  {name: '1957'},
  {name: '1956'},
  {name: '1955'},
  {name: '1954'},
  {name: '1953'},
  {name: '1952'},
  {name: '1951'},
  {name: '1950'},
  {name: '1949'},
  {name: '1948'},
  {name: '1947'},
  {name: '1946'},
  {name: '1945'},
  {name: '1944'},
  {name: '1943'},
  {name: '1942'},
  {name: '1941'},
  {name: '1940'},
  {name: '1939'},
  {name: '1938'},
  {name: '1937'},
  {name: '1936'},
  {name: '1935'},
  {name: '1934'},
  {name: '1933'},
  {name: '1932'},
  {name: '1931'},
  {name: '1930'},
  {name: '1929'},
  {name: '1928'},
  {name: '1927'},
  {name: '1926'},
  {name: '1925'},
  {name: '1924'},
  {name: '1923'},
  {name: '1922'},
];
