import {Dimensions, StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  keyboardAware: {
    flex: 1,
    backgroundColor: '#fff',
  },
  container: {
    width: '100%',
    height: Dimensions.get('window').height / 0.6,
  },
  buttonsContainer: {
    borderTopWidth: 0.6,
    paddingVertical: 20,
    borderTopColor: '#b3b3b3',
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: '90%',
    alignSelf: 'center',
    height: 120,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pressAbleStyle: {
    backgroundColor: '#607d8b',
    borderRadius: 10,
    width: '30%',
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 5,
    flexDirection: 'row',
  },
  facebookPressable: {
    backgroundColor: '#607d8b',
    borderRadius: 10,
    width: '30%',
    height: 45,
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 10,
    flexDirection: 'row',
  },
  pressableText: {
    fontSize: 16,
    color: '#fff',
  },
  pressableIcon: {
    marginHorizontal: 6,
  },
  headerTextContainer: {
    width: '97%',
    height: 150,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginTop: '5%',
  },
  creatAccountText: {
    color: '#263238',
    textTransform: 'uppercase',
    fontSize: 20,
    fontWeight: '700',
  },
  suggestionText: {
    textAlign: 'center',
    fontSize: 18,
    marginVertical: 10,
    color: '#212529',
    fontWeight: '400',
  },
  orTextContainer: {
    width: '100%',
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  orText: {
    color: '#263238',
    fontWeight: 'bold',
    fontSize: 20,
  },
  lastSectionContainer: {
    width: '100%',
    height: 430,
  },
  inputsAndButtonsContainer: {
    width: '100%',
    height: '50%',
  },
  firstNameTextContiner: {
    width: '29%',
    height: '18%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  firstNameText: {
    color: '#212529',
  },
  star: {
    color: '#ff4c52',
  },
  firstNameTextInput: {
    width: '90%',
    height: '25%',
    borderWidth: 0.6,
    borderRadius: 5,
    alignSelf: 'center',
  },
  lastNameTextContainer: {
    width: '29%',
    height: '18%',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: '5%',
  },
  lastNameTextInput: {
    width: '90%',
    height: '25%',
    borderWidth: 0.6,
    borderRadius: 5,
    alignSelf: 'center',
  },
  phoneTextContainer: {
    width: '22%',
    height: '18%',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: '5%',
  },
  emailTextContainer: {
    width: '35%',
    height: '18%',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: '5%',
  },
  passwordTextContainer: {
    width: '29%',
    height: '18%',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: '5%',
  },
  checkboxAndTextContainer: {
    width: '90%',
    height: 70,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    flexDirection: 'row',
  },
  checkboxIcon: {
    height: 37,
    marginHorizontal: 5,
  },
  bySubmittingText: {
    fontSize: 17,
  },
  createAccountButtonContainer: {
    width: '80%',
    height: 60,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  createAccountPressable: {
    width: '55%',
    height: 50,
    marginHorizontal: 6,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  createAccountPressableText: {
    color: '#fff',
    fontSize: 20,
  },
  eyeIconContainer: {
    position: 'absolute',
    top: 480,
    right: 19,
    bottom: 80,
    left: 280,
  },
  eyeIconPressable: {
    width: '100%',
    height: 55,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#006f44',
    borderTopRightRadius: 4,
    borderBottomRightRadius: 4,
  },
  errText: {
    fontSize: 16,
    paddingVertical: 10,
    color: 'red',
    textAlign: 'center',
  },
});

export default styles;
