import {Dimensions, StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0)',
  },
  scrollView: {
    flex: 1,
  },
  empHeadingContainer: {
    marginHorizontal: 15,
    width: '100%',
    height: 40,
    justifyContent: 'flex-end',
  },
  empHeading: {
    fontSize: 20,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    color: '#43425d',
  },
  headingContainer: {
    flexDirection: 'row',
    width: '100%',
    height: 40,
    alignItems: 'center',
    marginHorizontal: 15,
  },
  headingTextSlash: {
    marginHorizontal: 5,
  },
  headingText: {
    marginHorizontal: 5,
    color: '#6c757d',
  },
  activeEmployeesCard: {
    width: '90%',
    height: 130,
    backgroundColor: '#fff',
    elevation: 10,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
  },
  numOfActiveEmployees: {
    color: '#263238',
    fontWeight: '700',
    fontSize: 46,
    marginVertical: 5,
  },
  activeEmployeesHeading: {
    color: '#b3b3b3',
    fontWeight: '300',
    fontSize: 10,
    textTransform: 'uppercase',
  },
  totalEmployeesCard: {
    width: '90%',
    height: 130,
    backgroundColor: '#fff',
    elevation: 10,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    marginVertical: 20,
  },
  numOfTotalEmployees: {
    color: '#263238',
    fontWeight: '700',
    fontSize: 46,
    marginVertical: 5,
  },
  totalEmployeesHeading: {
    color: '#b3b3b3',
    fontWeight: '300',
    fontSize: 10,
    textTransform: 'uppercase',
  },
  card: {
    elevation: 5,
    width: '92%',
    backgroundColor: '#fff',
    alignSelf: 'center',
    marginVertical: 10,
  },
  cardHeadingContainer: {
    marginHorizontal: 15,
    marginVertical: 10,
  },
  line: {
    width: '100%',
    height: 0.3,
    backgroundColor: '#b3b3b3',
  },
  cardHeadingText: {
    textTransform: 'uppercase',
    fontSize: 20,
    fontWeight: 'bold',
  },
  searchEmployeesHeadingContainer: {
    marginHorizontal: 15,
    marginVertical: 10,
    alignItems: 'center',
    flexDirection: 'row',
  },
  pressableContainer: {
    marginHorizontal: 10,
  },
  emailTextContainer: {
    width: '21%',
    height: 35,
    justifyContent: 'center',
    alignItems: 'center',
  },
  firstNameText: {
    color: '#212529',
  },
  lastNameTextInput: {
    flexDirection: 'row',
    width: '90%',
    height: 45,
    borderWidth: 0.6,
    borderRadius: 5,
    alignItems: 'center',
    alignSelf: 'center',
  },
  departmentTextContainer: {
    width: '31%',
    height: 35,
    justifyContent: 'center',
    alignItems: 'center',
  },
  positionTextContainer: {
    width: '24%',
    height: 35,
    justifyContent: 'center',
    alignItems: 'center',
  },
  officeTextContainer: {
    width: '20%',
    height: 35,
    justifyContent: 'center',
    alignItems: 'center',
  },
  createAccountButtonContainer: {
    marginVertical: 10,
    width: '80%',
    height: 60,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  createAccountPressableText: {
    color: '#fff',
    fontSize: 20,
  },
  createAccountPressable: {
    width: '55%',
    height: 50,
    marginHorizontal: 6,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  clearPressable: {
    width: '55%',
    height: 50,
    marginHorizontal: 6,
    borderWidth: 1,
    borderColor: '#006f44',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  dropIconContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'flex-end',
    marginHorizontal: 10,
  },
  dropIcon: {
    marginBottom: -13,
  },
  itemsCard: {
    backgroundColor: '#f9f9fb',
    width: '85%',
    height: Dimensions.get('window').height / 2.7,
    marginVertical: 15,
    alignSelf: 'center',
    marginHorizontal: 9,
  },
  itemsContentContainer: {
    marginHorizontal: 10,
    marginVertical: 10,
  },
  userDPImageContainer: {
    width: 70,
    height: 70,
    borderWidth: 2,
    borderRadius: 35,
    borderColor: '#13bd7c',
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 10,
  },
  userDPImage: {
    width: 57,
    height: 57,
    borderRadius: 27,
  },
  activeTextParent: {
    width: '100%',
    alignItems: 'flex-end',
  },
  activeTextContainer: {
    width: 50,
    height: 22,
    borderRadius: 15,
    backgroundColor: '#13bd7c',
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 15,
  },
  activeText: {
    fontSize: 15,
    color: '#fff',
  },
  imageAndNameContainer: {
    flexDirection: 'row',
  },
  namePositionAndDepartmentContainer: {
    flexDirection: 'column',
    marginHorizontal: 15,
  },
  fistNameAndLastName: {
    fontSize: 16,
    marginVertical: 10,
    textTransform: 'capitalize',
    fontWeight: '500',
    color: '#263238',
  },
  text: {
    color: '#6c757d',
    fontSize: 12,
  },
  emailAndDOBContainer: {
    marginVertical: 15,
  },
  emailContainer: {
    flexDirection: 'row',
    marginVertical: 5,
  },
  icon: {
    marginHorizontal: 5,
  },
  email: {
    color: '#263238',
    fontSize: 15,
  },
  itemsPressable: {
    flexDirection: 'row',
    width: '90%',
    height: '17%',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
  },
  view: {
    fontSize: 16,
  },
  totalItems: {
    marginHorizontal: 10,
    marginVertical: 10,
  },
});

export default styles;
