import {StyleSheet} from 'react-native';
import tw from 'tailwind-react-native-classnames';

const styles = StyleSheet.create({
  container: tw`flex-1 bg-gray-100`,
  scrollView: tw`flex-1`,
  textContainer: tw`mt-5 ml-3 mb-2 items-center`,
  text: tw`text-lg text-black uppercase font-extrabold`,
  headingContainer: tw`flex-row`,
  slash: tw`ml-1.5`,
  headingText: tw`ml-2 text-gray-500 capitalize`,
  card: tw`w-11/12 min-h-0 flex-1 m-3 self-center bg-white shadow-md`,
  heading: tw`p-3 ml-2 mt-2 uppercase text-lg font-extrabold text-gray-600`,
  line: tw`w-full h-0.5 bg-gray-100`,
  cancelPressableContainer: tw`flex-1 justify-end items-end mr-3`,
  cancelPressable: tw`w-11/12 h-12 rounded justify-center items-center bg-red-500`,
  cancelPressableText: tw`text-white capitalize text-xs text-center`,
  itemCard: tw`w-10/12 min-h-0 flex-1 bg-gray-100 m-5 rounded pb-5`,
  editAndDeletePressableContainer: tw`flex-1 flex-row mt-6`,
  editPressable: tw`w-5/12 h-12 rounded justify-center items-center`,
  deletePressable: tw`w-5/12 h-12 rounded justify-center items-center ml-7`,
  editAndDeletePressableText: tw`capitalize text-sm text-center`,
  lableContainer: tw` justify-center items-end`,
  lableMain: tw`pr-2 pl-2 pb-0.5 pt-0.5 rounded-full mt-4 mr-1`,
  lableText: tw`text-white text-xs`,
  firstTextContainer: tw`ml-7`,
  titleText: tw`text-black text-lg font-extrabold`,
  subTitleText: tw`text-xs mt-2 text-gray-400 w-60`,
  dateText: tw`text-xs mt-1 text-gray-400 capitalize`,
  frequencyText: tw`text-xs mt-1 text-gray-400 capitalize`,
  lastTextContainer: tw`mt-7`,
  lastTexts: tw`text-gray-600 text-base`,
  tabsPressable: tw`p-4`,
  keyPerformacePressable: tw`p-5 items-center`,
  tabsText: tw`text-sm font-extrabold uppercase`,
  enableAndDisablePressableContainer: tw`flex-1 flex-row border-2 border-gray-100 mr-2 self-end p-0.5 rounded`,
  enablePressable: tw`w-4/12 h-12 rounded justify-center items-center`,
  disablePressable: tw`w-4/12 h-12 rounded justify-center items-center`,
  enableAndDisablePressableText: tw`capitalize text-lg text-center`,
  wouldYouLikeContainer: tw`bg-gray-50 m-2 pb-2`,
  wouldYouLike: tw`ml-3 mt-2 text-black text-base uppercase flex-1`,
  saveSettingsPressable: tw`w-5/12 h-12 rounded justify-center items-center self-center mb-4`,
  saveSettingsPressableText: tw`capitalize text-lg text-center text-white`,
  nameTextInput: tw`w-full h-12 border-2 border-gray-200 self-center rounded pl-2`,
  descriptionTextInput: tw`w-full h-32 border-2 border-gray-200 rounded pl-2`,
  textInputContainer: tw`m-3`,
  beginText: tw`pb-2 capitalize`,
  justify: tw`justify-center`,
  switchContainer: tw`items-center pl-4`,
  itemEnd: tw`items-end`,
  backColor: tw`bg-blue-100`,
  marginTop: tw`mt-2`,
  marginRight: tw`mr-7`,
  commentsText: tw`uppercase font-extrabold text-base text-black ml-2`,
  managersCommentContainer: tw`justify-end mr-3 mt-2`,
  shortDesc: tw`mt-3 ml-3`,
  addNewItem: tw`ml-3 mt-2`,
  addNewItemText: tw`text-sm capitalize`,
  titleAndShortDescCard: tw`w-full h-64 border-2 border-gray-200 rounded mt-2`,
  paddingLeftZero: tw`pl-0`,
  removeIconPressable: tw`w-8 h-9 border-2 border-gray-100 rounded self-end justify-center items-center relative right-4 bottom-5`,
  marginTopZero: tw`mt-0`,
  titleAndPointsRateCard: tw`w-full h-40 border-2 border-gray-200 rounded mt-2`,
  keyPerformanceIndicatorsCard: tw`w-full min-h-0 flex-1 border-2 border-gray-200 rounded mt-2`,
  testPressable: tw`w-4/12 h-12 rounded justify-center items-center`,
  itemCenter: tw`items-center`,
  marginRightTwo: tw`mr-2`,
  weCouldNotContainer: tw`bg-blue-100 h-10 mt-12 justify-center items-center mb-20`,
  weCouldNot: tw`text-sm`,
});

export default styles;
