import {Dimensions, StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  scrollView: {
    flex: 1,
  },
  userNameContiner: {
    marginHorizontal: 15,
    width: '100%',
    height: 40,
    justifyContent: 'flex-end',
  },
  userName: {
    fontSize: 20,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    color: '#43425d',
  },
  headingContainer: {
    flexDirection: 'row',
    width: '100%',
    height: 40,
    alignItems: 'center',
    marginHorizontal: 15,
  },
  headingTextSlash: {
    marginHorizontal: 5,
  },
  headingText: {
    marginHorizontal: 5,
    color: '#6c757d',
    textTransform: 'capitalize',
  },
  imageBack: {
    width: '95%',
    height: Dimensions.get('window').height / 2.2,
    marginHorizontal: 15,
  },
  contentContainer: {
    width: '90%',
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 10,
  },
  userProfile: {
    width: '40%',
    height: 120,
    borderRadius: 70,
    borderWidth: 0.6,
    borderColor: '#fff',
  },
  editIconContainer: {
    position: 'absolute',
    top: 80,
    bottom: 0,
    right: 80,
    left: 200,
  },
  editIconPressable: {
    width: 25,
    height: 25,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  imageBackUserNameContainer: {
    width: '90%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  imageBackUserName: {
    fontSize: 20,
    color: '#e9e9f0',
    fontWeight: '400',
    textTransform: 'capitalize',
  },
  email: {
    fontSize: 14,
    color: '#e9e9f0',
    fontWeight: '300',
    marginVertical: 10,
  },
  doBContainer: {
    width: '90%',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  icon: {
    marginHorizontal: 8,
  },
  userDOB: {
    fontSize: 14,
    color: '#e9e9f0',
    fontWeight: '300',
  },
  card: {
    elevation: 10,
    width: '90%',
    height: Dimensions.get('window').height / 3,
    backgroundColor: '#fff',
    alignSelf: 'center',
    marginVertical: 20,
  },
  cardHeadingContainer: {
    marginHorizontal: 20,
    marginVertical: 25,
    flexDirection: 'row',
  },
  cardHeadingText: {
    textTransform: 'uppercase',
    fontSize: 20,
    fontWeight: 'bold',
  },
  buttonsContainer: {
    flexDirection: 'row',
    flex: 1,
    flexWrap: 'wrap',
    justifyContent: 'space-around',
    alignItems: 'center',
    marginVertical: 20,
  },
  pressAbleStyle: {
    backgroundColor: '#607d8b',
    borderRadius: 10,
    width: '30%',
    height: '40%',
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 5,
    flexDirection: 'row',
  },
  facebookPressable: {
    backgroundColor: '#607d8b',
    borderRadius: 10,
    width: '30%',
    height: '40%',
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 10,
    flexDirection: 'row',
  },
  pressableText: {
    fontSize: 16,
    color: '#fff',
  },
  pressableIcon: {
    marginHorizontal: 6,
  },
  employmentCard: {
    elevation: 10,
    width: '90%',
    height: Dimensions.get('window').height / 2.5,
    backgroundColor: '#fff',
    alignSelf: 'center',
    marginVertical: 20,
  },
  employmentCardHeadingContainer: {
    marginHorizontal: 20,
    marginVertical: 25,
    flexDirection: 'row',
  },
  line: {
    width: '100%',
    height: '0.2%',
    backgroundColor: '#b3b3b3',
  },
  cardHeadingText: {
    textTransform: 'uppercase',
    fontSize: 20,
    fontWeight: 'bold',
  },
  profileDetailsContainer: {
    flexDirection: 'row',
    flex: 1,
  },
  profileDetailsContainerChild: {
    flex: 1,
    marginHorizontal: 20,
    marginVertical: 10,
    justifyContent: 'space-evenly',
  },
  employeeHeading: {
    color: '#263238',
    fontSize: 14,
  },
  employeePosition: {
    color: '#6c757d',
    fontSize: 14,
  },
  detailsContainer: {
    flex: 1,
    marginHorizontal: 15,
    justifyContent: 'space-evenly',
  },
  editContainer: {
    flex: 1,
    alignItems: 'flex-end',
  },
  itMyOwnCard: {
    elevation: 10,
    width: '90%',
    height: Dimensions.get('window').height / 2,
    backgroundColor: '#fff',
    alignSelf: 'center',
    marginVertical: 10,
  },
  itMyOwn: {
    fontSize: 23,
    color: '#6c757d',
    textTransform: 'uppercase',
    fontWeight: '700',
  },
  hobbiesContainer: {
    flex: 1,
    justifyContent: 'space-around',
    marginHorizontal: 20,
    marginVertical: 10,
  },
  managerNotesCard: {
    elevation: 10,
    width: '90%',
    height: Dimensions.get('window').height / 2.8,
    backgroundColor: '#fff',
    alignSelf: 'center',
    marginVertical: 10,
  },
  managerNotesTextContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  managerNotesBackground: {
    width: '70%',
    height: 50,
    borderRadius: 10,
    backgroundColor: '#8dd9e8',
    justifyContent: 'center',
    alignItems: 'center',
  },
  managerNotesText: {
    color: '#4d4f5c',
    fontWeight: '400',
    fontSize: 16,
  },
  infoCard: {
    elevation: 10,
    flex: 1,
    width: '90%',
    marginHorizontal: 19,
    paddingVertical: 10,
    backgroundColor: '#fff',
    alignSelf: 'center',
    marginVertical: 10,
  },
  infoText: {
    textTransform: 'uppercase',
    fontWeight: '700',
    fontSize: 16,
  },
  tabsContainer: {
    marginHorizontal: 10,
    marginVertical: 10,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  tabs: {
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  timeOffAndHolidays: {
    marginVertical: 5,
  },
  upcomingTimeOff: {
    marginHorizontal: 10,
  },
  upcomingTimeOffText: {
    color: '#263238',
    fontSize: 16,
    textTransform: 'uppercase',
    marginVertical: 10,
  },
  notFindBackground: {
    width: '100%',
    height: 50,
    backgroundColor: '#f7d87a',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  notFindText: {
    color: '#9d6700',
    fontSize: 16,
  },
  timeOffcardHeadingContainer: {
    marginHorizontal: 15,
    marginVertical: 10,
  },
  cardHeadingText: {
    textTransform: 'uppercase',
    fontSize: 20,
    fontWeight: 'bold',
  },
  timeOffInfoCard: {
    flex: 1,
    // height: Dimensions.get('window').height / 3,
    backgroundColor: '#fff',
    elevation: 5,
    borderRadius: 5,
    marginVertical: 10,
    marginHorizontal: 50,
  },
  textContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 10,
  },
  holiday: {
    color: '#263238',
    textTransform: 'uppercase',
    fontSize: 14,
  },
  numOfHoliday: {
    fontSize: 46,
    color: '#006f44',
    fontWeight: '400',
  },
  hoursAvailable: {
    color: '#808495',
    textTransform: 'uppercase',
    fontWeight: '300',
    fontSize: 10,
  },
  headingOfTotalHours: {
    color: '#808495',
    textTransform: 'uppercase',
    fontSize: 10,
    marginVertical: 5,
  },
  numOfTotalHours: {
    fontSize: 12,
    color: '#263238',
    fontWeight: '400',
  },
  roundCircleContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  roundCircle: {
    width: 110,
    height: 110,
    borderRadius: 60,
    borderWidth: 7,
    borderColor: '#f5f5f5',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginVertical: 10,
  },
  numOfUsedHours: {
    color: 'red',
    fontSize: 30,
  },
  historyHeading: {
    marginVertical: 10,
    marginHorizontal: 17,
  },
  historyText: {
    textTransform: 'uppercase',
    fontSize: 20,
    color: '#263238',
    fontWeight: 'bold',
  },
  departmentTextContainer: {
    width: '31%',
    height: 35,
    justifyContent: 'center',
    alignItems: 'center',
  },
  firstNameText: {
    color: '#212529',
  },
  lastNameTextInput: {
    flexDirection: 'row',
    width: '90%',
    height: 45,
    borderWidth: 0.6,
    borderRadius: 5,
    alignItems: 'center',
    alignSelf: 'center',
  },
  dropIconContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'flex-end',
    marginHorizontal: 10,
  },
  dropIcon: {
    marginBottom: -13,
  },
  positionTextContainer: {
    width: '24%',
    height: 35,
    justifyContent: 'center',
    alignItems: 'center',
  },
  createAccountButtonContainer: {
    marginVertical: 10,
    width: '80%',
    height: 60,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  clearPressable: {
    width: '55%',
    height: 50,
    marginHorizontal: 6,
    borderWidth: 1,
    borderColor: '#006f44',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  createAccountPressableText: {
    color: '#fff',
    fontSize: 20,
  },
  createAccountPressable: {
    width: '55%',
    height: 50,
    marginHorizontal: 6,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  weCouldNotContainer: {
    width: '90%',
    height: 40,
    backgroundColor: '#f8f9fa',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  weCouldNot: {
    fontSize: 16,
  },
  infoHeading: {
    fontSize: 16,
    color: '#263238',
    fontWeight: '400',
    textTransform: 'capitalize',
    marginVertical: 8,
  },
  infoHeadingExplain: {
    fontSize: 15,
    color: 'rgba(0,0,0,0.5)',
    textTransform: 'none',
    marginVertical: 8,
  },
  addLicensesText: {
    color: '#fff',
    fontSize: 20,
    textTransform: 'capitalize',
  },
  addLicensesPressable: {
    width: '90%',
    height: 50,
    marginHorizontal: 6,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  licensesAndCertifications: {
    width: '100%',
    alignItems: 'center',
    marginVertical: 20,
  },
  licensesAndCertificationsText: {
    fontSize: 20,
    textTransform: 'uppercase',
    color: '#263238',
  },
  mapRowContainer: {
    flex: 1,
    flexDirection: 'row',
    marginVertical: 20,
  },
  mapItemContainer: {
    flex: 1,
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  mapItem: {
    textTransform: 'uppercase',
    color: '#fff',
  },
  mapItemBackground: {
    width: 30,
    height: 30,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  submitText: {
    color: '#fff',
    fontSize: 20,
    textTransform: 'capitalize',
  },
  submitPressable: {
    width: '30%',
    height: 50,
    marginHorizontal: 10,
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  mondayTextContainer: {
    marginHorizontal: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  mondayText: {
    color: '#212529',
  },
  mondayTextInput: {
    flexDirection: 'row',
    width: '70%',
    height: 45,
    borderWidth: 0.6,
    borderRadius: 5,
    alignItems: 'center',
    marginVertical: 10,
    marginHorizontal: 10,
  },
  dropIconMain: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'flex-end',
    marginHorizontal: 10,
  },
  myDropIcon: {
    marginBottom: -13,
  },
  ToTextContainer: {
    marginHorizontal: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  mondayContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 10,
    paddingVertical: 10,
  },
  directionRow: {
    flexDirection: 'row',
  },
  contactContainer: {
    flex: 1,
    marginHorizontal: 20,
    marginVertical: 10,
  },
  contactItems: {
    flexDirection: 'row',
    marginVertical: 10,
  },
  contactHeading: {
    fontSize: 15,
    textTransform: 'capitalize',
    fontWeight: 'bold',
    marginHorizontal: 5,
  },
});

export default styles;
